### ISSUE TITLE
[QUESTION] Is there a way to run custom programs in Aura.

### ISSUE THREAD

**Issue by TFTWPhoenix** [aura-systems/Aura-Operating-System#181]
Is it possible to run custom programs in Aura? Such as those written in C or Assembly?

**Comment by valentinbreiz** [comment]
Hello @TFTWPhoenix, we used to have a binary loader working on Aura. We could run C and assembly compiled programs but we abandoned this feature due to real security issues and architecture non-senses. If you still want to take a look on how we did that you can see this pull request: https://github.com/aura-systems/Aura-Operating-System/pull/38

And this build environment: https://github.com/aura-systems/Aura-Executable

If you want some explanations on how this works I can do a little summary ;)

**Comment by TFTWPhoenix** [comment]
Thanks for the response @valentinbreiz. I have a suggestion on how it could be possible to re-implement such a feature. It could be possible to run everything inside of a "hypervisor" which isolates the program from other memory and critical files and disables certain features for security. This approach has a significant performance hit however. I would love to see ELF executable support in Aura as this would cement the operating system as a tinkerer's dream.

**Comment by valentinbreiz** [comment]
Yes, running a program in a secured environment, a sandbox or something like that can be a solution
But thinking about executables without paging, multitask or paging achieved seems a bit precipitated.
But, if you want to use ELF on Cosmos or Aura you can use https://github.com/Myvar/CosmosELF it is working!

**Comment by TFTWPhoenix** [comment]
@valentinbreiz thanks for the working example of a Cosmos ELF loader. I had no idea there were any modern working ones.
